### PR TITLE
Handle nested containers

### PR DESCRIPTION
**Pull request by aswan**
Note this is based on fix-zson-containers, not master.  It will need #34 (or its successor) to be finished first.

### CODE REVIEW

**Comment by aswan** [comment]
> Looks good but I think `zeek.NewRawAndTsFromJSON` also needs updating?

Good catch.  To be clear, this is a json value with keys like `"foo.bar"` instead of nested objects.
Also, it occurred to me separately that I should fix groupby so that e.g., `count() by id.orig_h` doesn't break.

**Comment by henridf** [comment]
> I think zeek.NewRawAndTsFromJSON also needs updating?

To clarify this a little, JSON records coming out of Zeek look like 

```json

{
"ts":"2017-03-24T19:59:23.670330Z",
"uid":"CsUYQG1OKdAM4oCt84",
"id.orig_h":"10.255.255.69",
"id.orig_p":51542,
"id.resp_h":"35.163.117.18",
"id.resp_p":80, 
.
.
}
```

(And we should at some point also handle json records with actual nesting but that's a separate issue).

**Comment by aswan** [comment]
Oh and `cut` too.  Sigh...

**Comment by henridf** [comment]
@aswan any proc that refers to a field right? `sort`, `uniq` ...

**Comment by aswan** [comment]
> Looks good but I think zeek.NewRawAndTsFromJSON also needs updating?

@henridf it looks like there's no way to actually get to this function with `zq` at the moment?  or were you thinking of something else?

**Comment by aswan** [comment]
> @aswan any proc that refers to a field right? sort, uniq ...

Yes, `sort` and `top` but `uniq` doesn't refer to fields?

**Comment by henridf** [comment]
> Yes, sort and top but uniq doesn't refer to fields?

Oh duh you're right it doesn't.

> @henridf it looks like there's no way to actually get to this function with zq at the moment? or were you thinking of something else?

Yes I was thinking of downstream users of this package.

**Comment by aswan** [comment]
still have some work to do here, will start fresh when this is actually ready.

**Pull request closed without merging**
