### PR TITLE
test js parser

### PR DESCRIPTION
**Pull request by mattnibs**
Add test coverage for js parser. Test for parser executes a query
in node, then runs ast.Unpack on the output and compares the derrived
proc from that of the go parser.

Also:
- Move all javascript code into the ./js directory
- Update package.json to include pegjs as a dependency
- Update make test-unit to ensure all zql related stuff
is built before running.
- Move go helpers into its own package. This is so they work the same as the node helpers and we don't have to embed all the javascript code into the peg parser.

### CODE REVIEW

**Comment by aswan** [comment]
Can you explain the rationale for moving the parser code around?  The grammar and the language-specific support files are quite tightly coupled and in my experience it is quite common to edit them together.  I think that unless there's some very compelling reason to move them around, we'd be better off keeping them as-is.

**Comment by mattnibs** [comment]
> Can you explain the rationale for moving the parser code around?

I assume you mean the parser support stuff, not the fact that I moved reglob and the compiled js parser to `js`? @nwt had a similar comment. I did this originally because I didn't see a way of getting `zql.js` to do imports correctly w/out doing some hideous browserify, throw a nest of js into the zql build artifact, but I just thought of a way to do this.

I still think putting reglob.js, cli.js, and the zql.js build artifact is the right way to go (`parser-support.js` can remain where it was in the zql dir).

**Comment by nwt** [comment]
I definitely want zql.js test coverage, but
* I think moving ZQL-related code out of /zql/ and into /js/ and /Makefile is unintuitive. 
* I don't think https://github.com/mccanne/zq/pull/153/files#diff-103715cf0e3db43f218c7235fd2a18fbR102-R134 is an improvement over `#include "parser-support.js"`.

I think you should scale this back to just the zql/zql_test.go change.

**Comment by mattnibs** [comment]
I'm going to redo this one and keep it simpler

**Comment by alfred-landrum** [comment]
as discussed with @mattnibs , closing this PR since any future efforts will take a different approach.

**Pull request closed without merging**
