### PR TITLE
add tools dependencies for parsing

### PR DESCRIPTION
**Pull request by alfred-landrum**
This is based on the tool dependency tracking suggestions at the Go
modules faq:

https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

### CODE REVIEW

**Comment by alfred-landrum** [comment]
This replaces the earlier approach using Docker: https://github.com/mccanne/zq/pull/272

**Comment by aswan** [comment]
I don't really understand how this works.  In particular, the distinction between the regular downloading of packages that happens during a build and the `go install` step?  Also since that just uses a shared directory ($GO/bin), this system doesn't seem very robust if somebody wants to build two different go packages that use two different versions of the same external tool.
@nwt do you know how this is meant to work and can you clear this up a bit?

**Comment by nwt** [comment]
@aswan: The distinction is that typical go invocations won't download github.com/mna/pigeon because it isn't imported by any file you're likely to compile (`// +build tools` in tools.go will probably exclude that file), but `go install github.com/mna/pigeon` will download it because you're explicitly asking for it, and it'll respect the version in go.mod.

**Comment by aswan** [comment]
I've still got a bunch of questions about the "standard" go way to do this but I don't think it matters if we're going with #293

**Comment by alfred-landrum** [comment]
Closing in favor of https://github.com/mccanne/zq/pull/293 .

**Pull request closed without merging**
