### PR TITLE
Implement Alias Type

### PR DESCRIPTION
**Pull request by mattnibs**
Done according to the zng spec. Includes end-to-end reading and
writing for bzng, zng and zjson. Support for aliases added to
sort, reducer, and groupby procs.

TODO (in this pr):
- [x] zjson support

### CODE REVIEW

**Comment by henridf** [comment]
nit: I think the "split zeek/zng readers" commit deserves its own PR.

**Comment by mccanne** [comment]
> nit: I think the "split zeek/zng readers" commit deserves its own PR.

Yeah, pretty easy to factor our, merge, and rebase.

**Comment by mattnibs** [comment]
> nit: I think the "split zeek/zng readers" commit deserves its own PR.

It needs to be done because otherwise I would have to use some annoying regex rule to get alias parsing working. It could be done as a tangential pr but it would hold up this pr while it waits to get merged. If you guys really feel strongly about this I can do this, but this has already been a complicated piece of work and I would appreciate approval as-is (once I commit my zjson changes).

**Comment by henridf** [comment]
if the rebase isn't clean then sure i say go ahead and keep it here.

**Pull request merged**
